language: rust

os:
  - linux
  - osx

dist: trusty

addons:
  apt:
    packages:
      - libsdl2-dev

before_install:
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install sdl2; fi"

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never
    on_failure: always
