language: rust
dist: trusty
addons:
  apt:
    packages:
      - libsdl2-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
    on_failure: always
