[package]
name = "bakervm"
version = "0.1.0"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]
description = "A virtual machine for classic point-and-click adventure games"
repository = "https://github.com/bakervm/bakervm"
readme = "README.md"
license = "MIT"

[dependencies]
bakervm-definitions = { path = "definitions" }
clap = "2.23.3"
error-chain = "0.10.0"
sdl2 = "0.29.1"
ieee754 = "0.2.1"

[[bin]]
name = "bakervm"
path = "vm/main.rs"

[[bin]]
name = "basm"
path = "asm/main.rs"
