[package]
name = "bakervm"
version = "0.2.0"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]
description = "A virtual machine for classic point-and-click adventure games"
repository = "https://github.com/bakervm/bakervm"
readme = "README.md"
license = "MIT"

[dependencies]
clap = "2.23.3"
error-chain = "0.10.0"
sdl2 = "0.29.1"
ieee754 = "0.2.1"

[lib]
name = "definitions"
path = "definitions/lib.rs"

[[bin]]
name = "bakervm"
path = "vm/main.rs"

[[bin]]
name = "basm"
path = "asm/main.rs"
