[package]
name = "bakervm"
version = "0.2.5"
authors = ["Julian Laubstein <contact@julianlaubstein.de>"]
description = "A virtual machine for classic point-and-click adventure games"
repository = "https://github.com/bakervm/bakervm"
readme = "README.md"
license = "MIT"

[dependencies]
clap = "*"
error-chain = "*"
sdl2 = "*"
ieee754 = "*"
num = "*"

[lib]
name = "definitions"
path = "definitions/lib.rs"

[[bin]]
name = "bakervm"
path = "bakervm/main.rs"

[[bin]]
name = "basm"
path = "basm/main.rs"
