reorder_imports = true
wrap_comments = true
reorder_imported_names = true
chain_one_line_max = 100
closure_block_indent_threshold = 0
fn_args_density = "Compressed"
array_layout = "Block"
fn_call_style = "Block"
fn_args_layout = "Block"
chain_indent = "Block"
